- hosts: all 
  become: yes
  become_user: root 
  gather_facts: yes

  tasks:
    - name: Disable swap & Add kernel Parameters
      shell: |
                sudo swapoff -a
                sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    
    - name: Create containerd files
      shell: |
                sudo tee /etc/modules-load.d/containerd.conf <<EOF
                overlay
                br_netfilter
                EOF
                sudo modprobe overlay
                sudo modprobe br_netfilter

    - name: Set kernel parameters for kubernetes to run 
      shell: |
                sudo tee /etc/sysctl.d/kubernetes.conf <<EOT
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                EOT 

    - name: Reload parameters
      command: sudo sysctl --system 

    - name: update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: download containerd-repo 
      apt:
        pkg:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https 
          - ca-certificates
        state: latest
        update_cache: true

      - name: enable containerd-repo 
      shell: |
                sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install containerd and containerd tools
      apt:
        pkg:
          - containerd.io
        state: latest
        update_cache: true

    - name: Configure containerd and containerd tools
      shell: |
                containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
                sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

    - name: Restart containerd and containerd tools
      shell: |
                sudo systemctl restart containerd
                sudo systemctl enable containerd

    - name: Add Apt Repo for K8s
      shell: |
                curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
                echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: update cache
      apt:
          update_cache: yes
          cache_valid_time: 3600

    - name: Install K8s
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        update_cache: true

    - name: Hold installs
      shell: |
                sudo apt-mark hold kubelet kubeadm kubectl