- hosts: master
  become: yes

  tasks:
    - name: Create kubeconfig fle
      shell: | 
                mkdir -p $HOME/.kube
                sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
                sudo chown $(id -u):$(id -g) $HOME/.kube/config 

    - name: Install calico Pod network
      become: yes
      become_user: k8sadmin
      shell: |
                 kubectl apply -f kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/tigera-operator.yaml
                 curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/custom-resources.yaml -O
                 sed -i 's/cidr: 192\.168\.0\.0\/16/cidr: 10.10.0.0\/16/g' custom-resources.yaml
                 kubectl create -f custom-resources.yaml